source 'http://git.guaniuwu.cn/XMPods/XMSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'

target ‘TaoMengMall’ do
# Uncomment the next line if you're using Swift or would like to use dynamic frameworks
# use_frameworks!

# Pods for CarKeeper
pod 'XMMegaBase'
pod 'XMLocation'
pod 'UMengAnalytics'
pod 'UMengMessage'
#pod 'ZXing', '~> 2.3'
pod 'XMAlipaySDK'
pod 'WeiboSDK'
pod 'XMTencentOpenApiSDK'
pod 'UICountingLabel','~> 1.2.0'
end
