platform :ios, ‘8.0’

target 'SD' do

	pod "AFNetworking", "~> 2.0"

	pod ’SDWebImage’
	
	pod ‘YYModel’
    
    pod 'AliyunOSSiOS', '~> 2.6.0'

    pod 'SVProgressHUD'
    
    pod 'UMengAnalytics-NO-IDFA'


    pod ‘UMengUShare/UI’
    
    
    # 集成微信(精简版0.2M)
    pod ‘UMengUShare/Social/ReducedWeChat'
    
    # 集成新浪微博(精简版1M)
    pod ‘UMengUShare/Social/ReducedSina'
    
    # 集成QQ(精简版0.5M)
    pod ‘UMengUShare/Social/ReducedQQ'
    
    pod 'Masonry', '~> 1.0.2'
    pod 'UITableView+FDTemplateLayoutCell', '~>1.6'
    
    pod 'RealReachability'
    

end






